// <auto-generated />
using Doctorantura.App.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Doctorantura.App.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220928011229_finit")]
    partial class finit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Doctorantura.App.Models.Column", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Row")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Columns");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "K1",
                            Row = 1
                        },
                        new
                        {
                            ID = 2,
                            Name = "K2",
                            Row = 2
                        },
                        new
                        {
                            ID = 3,
                            Name = "K3",
                            Row = 3
                        },
                        new
                        {
                            ID = 4,
                            Name = "K4",
                            Row = 4
                        },
                        new
                        {
                            ID = 5,
                            Name = "K5",
                            Row = 5
                        },
                        new
                        {
                            ID = 6,
                            Name = "K6",
                            Row = 6
                        },
                        new
                        {
                            ID = 7,
                            Name = "K7",
                            Row = 7
                        },
                        new
                        {
                            ID = 8,
                            Name = "K8",
                            Row = 8
                        });
                });

            modelBuilder.Entity("Doctorantura.App.Models.ColumnLine", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ColumnId")
                        .HasColumnType("int");

                    b.Property<int>("LineId")
                        .HasColumnType("int");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.HasIndex("ColumnId");

                    b.HasIndex("LineId");

                    b.ToTable("ColumnsLines");
                });

            modelBuilder.Entity("Doctorantura.App.Models.Line", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Row")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Lines");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "K1",
                            Row = 1
                        },
                        new
                        {
                            ID = 2,
                            Name = "K2",
                            Row = 2
                        },
                        new
                        {
                            ID = 3,
                            Name = "K3",
                            Row = 3
                        },
                        new
                        {
                            ID = 4,
                            Name = "K4",
                            Row = 4
                        },
                        new
                        {
                            ID = 5,
                            Name = "K5",
                            Row = 5
                        },
                        new
                        {
                            ID = 6,
                            Name = "K6",
                            Row = 6
                        },
                        new
                        {
                            ID = 7,
                            Name = "K7",
                            Row = 7
                        },
                        new
                        {
                            ID = 8,
                            Name = "K8",
                            Row = 8
                        });
                });

            modelBuilder.Entity("Doctorantura.App.Models.ColumnLine", b =>
                {
                    b.HasOne("Doctorantura.App.Models.Column", "Column")
                        .WithMany()
                        .HasForeignKey("ColumnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Doctorantura.App.Models.Line", "Line")
                        .WithMany("ColumnsLines")
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
